# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk11

services:
  - postgresql

before_install:
  - psql -c 'create database storage;' -U postgres


env:
  global:
    - CODECOV_TOKEN="50dd527c-4f65-47cd-a830-facd98abb5b9"

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      -r.m.nick@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always